---
title: "Traffic_Crashes_Linear_Regression"
author: "Divya Sharma (ds655)"
format: pdf
editor: visual
jupyter: ir
---

```{r}
library(dplyr, quietly = T)
```

```{r}
base_data <- readRDS(file='C:/Users/divya/OneDrive/Documents/Duke/MIDS/Semester 1/IDS 702 - Modeling and Representation of Data/Group_Project_Traffic_Crashes/Resources/df_cleaned_chicago_crashes_v2.rds')
head(base_data)
```

```{r}
model <- lm(police_notified_time ~
              #crash_date +
              hr_of_day +
              day_of_week +
              month_of_year +
              speed_limit +
              weather_condition +
              trafficway_type +
              roadway_surface_cond +
              num_units +
              dist_to_dt +
              #temp +
              precipitation +
              snow +
              snowdepth +
              windspeed +
              visibility +
              damage_class
              , data = base_data)
summary(model)
```

```{r}
# Set up a 2x2 grid for the plots
par(mfrow = c(2, 2))

# Generate the four diagnostic plots
plot(model)
```

```{r}
# Set up a 2x2 grid for the plots
par(mfrow = c(2, 2))

# Generate the Residuals vs Fitted plot with a title
plot(model, which = 1, main = "Residuals vs Fitted")

# Generate the Normal Q-Q plot with a title
plot(model, which = 2, main = "Normal Q-Q")

# Generate the Scale-Location plot with a title
plot(model, which = 3, main = "Scale-Location")

# Generate the Residuals vs Leverage plot with a title
plot(model, which = 4, main = "Residuals vs Leverage")
```

```{r}
plot(model, which = 1)
```

```{r}
plot(model, which = 2)
```

```{r}
plot(model, which = 3)
```

```{r}
plot(model, which = 4)
```

```{r}
car::vif(model)
```
